---
title: "Decision Trees"
author: "Coreys Notes"
output:
  html_document:
    number_sections: true
    toc: true
    toc_depth: 3
---

```{r}
library(rpart)
library(rpart.plot)
library(caret)
```

# Regression Tree

```{r}
train <- read.csv("train.csv")
```

```{r}
regressionTree <- rpart(SalePrice~.,data=train,method = "anova")
rpart.plot(regressionTree)
plotcp(regressionTree)
```


```{r}

m2 <- rpart(
    formula = SalePrice ~ .,
    data    = train,
    method  = "anova", 
    control = list(cp = .1,xval=5)
)
rpart.plot(m2)
```

Tuning Parameters:

minsplit: minimum number of observations required to make a split.

maxdepth: maximum number of internal nodes between the root node and the terminal node. 

```{r}
m3 <- rpart(
    formula = SalePrice ~ .,
    data    = train,
    method  = "anova", 
    control = list(minsplit = 10, maxdepth = 12, xval = 10)
)
rpart.plot(m3)
```

# Classification Tree

```{r}
mydf <- iris[1:100,]
head(mydf)

classificationTree <- rpart(Species~.,data=mydf,method="class")
rpart.plot(classificationTree)

confusionMatrix <- table(mydf$Species,predict(classificationTree,mydf,type="class"))
confusionMatrix

tune_fit <- rpart(Species~., data = mydf, method = 'class', control = rpart.control(minsplit = 4,
    minbucket = round(5 / 3),
    maxdepth = 3,
    cp = 0))

tune_fit
```


# Bagging 

```{r}
ctrl <- trainControl(method = "cv",  number = 10)

bagged_cv <- train(
  SalePrice ~ .,
  data = train[,c("OverallQual","OverallCond","SalePrice")],
  method = "treebag",
  trControl = ctrl,
  importance = TRUE
  )

bagged_cv
plot(varImp(bagged_cv))
```



# Random Forest

- use p/3 for regression

- $\sqrt{p}$ for classification

```{r}
library(randomForest)

mydf <- iris
set.seed(222)
rf <- randomForest(Species~.,data=mydf,proximity=TRUE)
rf
plot(rf)
```

```{r}
set.seed(1)
rf_random <- train(Species ~ .,
                   data = mydf,
                   method = 'rf',
                   metric = 'Accuracy',
                   tuneLength  = 3, 
                   trControl = ctrl)
plot(rf_random)
```


```{r}
modellist <- list()
for (ntree in c(1000,1500,2000,2500)){
  set.seed(123)
  fit <- train(Species~.,
               data = mydf,
               method = 'rf',
               metric = 'Accuracy',
               trControl = ctrl,
               ntree = ntree)
  key <- toString(ntree)
  print(key)
  modellist[[key]] <- fit
}
modellist
modellist['1000']
modellist[[1]]
results <- resamples(modellist)
summary(results)
```




















